name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  quality-assurance:    
    name: Quality Assurance Real Chat ยบ
    uses: ./.github/workflows/pr.yml
