name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    # services:
    #   db:
    #     image: postgres:15
    #     env:
    #       POSTGRES_DB: hello_django
    #       POSTGRES_USER: hello_django
    #       POSTGRES_PASSWORD: hello_django_dev
    container: python:3.11.4-buster
    steps:

      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        # env:
        #   SONAR_TOKEN: ${{secrets.SONAR_TOKEN}} // Sonar Token generated
        #   SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}} // Example 
      
    #   - name: Give ownership
    #     run: git config --global --add safe.directory /__w/rtchat/rtchat

    #   - name: Install make
    #     run: apt-get update && apt-get install -y make            

    #   - name: Install Dependencies
    #     run: make install && make install-pre-commit

    #   - name: Lint
    #     run: make lint

    #   - name: Test
    #     run: make test