name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    # services:
    #   db:
    #     image: postgres:15
    #     env:
    #       POSTGRES_DB: hello
    #       POSTGRES_USER: hello
    #       POSTGRES_PASSWORD: hello_dev
    container: python:3.11.4-buster
    steps:

      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}} // Sonar Token generated
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}} // Example 